# Generated by Django 5.0.7 on 2024-08-19 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0003_alter_property_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='image',
            field=models.URLField(blank=True, max_length=100),
        ),
    ]
